// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DotVariable-0]
	_ = x[DollarVariable-1]
	_ = x[Keyword-2]
	_ = x[Function-3]
	_ = x[Identifier-4]
	_ = x[Assignment-5]
	_ = x[DeclarationAssignment-6]
	_ = x[StringLit-7]
	_ = x[Character-8]
	_ = x[Number-9]
	_ = x[Decimal-10]
	_ = x[ComplexNumber-11]
	_ = x[Boolean-12]
	_ = x[EqualComparison-13]
	_ = x[Pipe-14]
	_ = x[Comma-15]
	_ = x[LeftParen-16]
	_ = x[RightParen-17]
	_ = x[Comment-18]
	_ = x[SpaceEater-19]
	_ = x[Eol-20]
	_ = x[Eof-21]
	_ = x[StaticGroup-22]
	_ = x[ExpandableGroup-23]
	_ = x[NotFound-24]
	_ = x[Unexpected-25]
}

const _Kind_name = "DotVariableDollarVariableKeywordFunctionIdentifierAssignmentDeclarationAssignmentStringLitCharacterNumberDecimalComplexNumberBooleanEqualComparisonPipeCommaLeftParenRightParenCommentSpaceEaterEolEofStaticGroupExpandableGroupNotFoundUnexpected"

var _Kind_index = [...]uint8{0, 11, 25, 32, 40, 50, 60, 81, 90, 99, 105, 112, 125, 132, 147, 151, 156, 165, 175, 182, 192, 195, 198, 209, 224, 232, 242}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
