beans:
  clickup:
    list_id: "901112937048"
    type_mapping:
      milestone: 1 # milestone
      epic: 1002 # project
      feature: 0 # Task (default)
      bug: 1001
      task: 0 # Task (default)
    status_mapping:
      draft: "not started"
      todo: "not started"
      in-progress: "in progress"
      completed: "completed"
      scrapped: "completed"
    custom_fields:
      bean_id: "a0b0c69a-d036-4031-9deb-4ecc4cfa3e55"
      created_at: "d3adc5e1-eedf-46e0-b5d5-a4dce3a0666b"
